### ISSUE TITLE
Can i maintain this?

### ISSUE THREAD

**Issue by vsnthdev** [angeal185/ghost-minify-output#1]
I see the instructions are out of date. Is a PR with updated README, dependencies welcomed?

**Comment by angeal185** [comment]
This was just meant as a personal reference for a missing basic feature that was requested for a few jobs a few years ago. If they still don't have this feature we could make a proper module of it. id have to take a look at how far they have progressed.

**Comment by angeal185** [comment]
Sorry they have turned a bit too corporate for my free time. feel free to use this code to make your own module though.

**Comment by vsnthdev** [comment]
Great! Thanks for taking time to respond to me.
I will create a proper module with automatic installation for Ghost.

**Comment by angeal185** [comment]
no worries. btw, ghost is a cms that is duck taped together from other modules so if you look in the node_modules you will be able to build your own minify module from within the 1000+ packages it requires.

**Comment by vsnthdev** [comment]
🤣 Oh yeah!

By the way, do you use Discord? Just so that we can talk a bit more on Ghost 😀

**Comment by angeal185** [comment]
angeal185#7370

**Comment by vsnthdev** [comment]
I have sent you a friend request 😅
